// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLService is an autogenerated mock type for the URLService type
type URLService struct {
	mock.Mock
}

// GetOrCreate provides a mock function with given fields: origURL
func (_m *URLService) GetOrCreate(origURL string) string {
	ret := _m.Called(origURL)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(origURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetOrigURL provides a mock function with given fields: shortID
func (_m *URLService) GetOrigURL(shortID string) string {
	ret := _m.Called(shortID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrigURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(shortID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewURLService creates a new instance of URLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLService {
	mock := &URLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
