// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetOrigByShort provides a mock function with given fields: short
func (_m *Repository) GetOrigByShort(short string) string {
	ret := _m.Called(short)

	if len(ret) == 0 {
		panic("no return value specified for GetOrigByShort")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(short)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetShortByOrig provides a mock function with given fields: orig
func (_m *Repository) GetShortByOrig(orig string) string {
	ret := _m.Called(orig)

	if len(ret) == 0 {
		panic("no return value specified for GetShortByOrig")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(orig)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SaveIfNotTaken provides a mock function with given fields: orig, short
func (_m *Repository) SaveIfNotTaken(orig string, short string) (string, error) {
	ret := _m.Called(orig, short)

	if len(ret) == 0 {
		panic("no return value specified for SaveIfNotTaken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(orig, short)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(orig, short)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(orig, short)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
